version: '3'

services:
    ml-service:
        build: ./ml-service
        ports:
            - '5000:5000'

    spring-api:
        build: ./springboot-api
        ports:
            - '8080:8080'
        depends_on:
            - ml-service
